### ISSUE TITLE
Audit: fix low severity issues

### ISSUE THREAD

**Issue by rndquu** [pavlovcik/uad-ui#874]
There are a bunch of low severity issues caught by auditors which are nice to fix. This is a low priority issue.

- [x] https://github.com/sherlock-audit/2023-12-ubiquity-judging/issues/21 (removing `diamondCut` by accident)
- [x] https://github.com/sherlock-audit/2023-12-ubiquity-judging/issues/29 (disable `collectRedemption()` if collateral is disabled)
- [x] https://github.com/sherlock-audit/2023-12-ubiquity-judging/issues/33 (more strict `redemptionDelayBlocks`)
- [x] https://github.com/sherlock-audit/2023-12-ubiquity-judging/issues/62 (set collateral chainlink price feed by index, admin may accidentally make the pool insolvent)
- [x] ~~https://github.com/sherlock-audit/2023-12-ubiquity-judging/issues/71~~ (missing `whenNotPaused`) - issue invalid due to different pause mechanism used. Marked as `Sponsor Disputed`, `Won't Fix` 
- [x] https://github.com/sherlock-audit/2023-12-ubiquity-judging/issues/119 (missing `notReentrant modifier`, not sure that it should be placed in the diamon's fallback, but worth to check all facet methods)
- [x] https://github.com/sherlock-audit/2023-12-ubiquity-judging/issues/121 (wrong implementation of [ERC-7201](https://eips.ethereum.org/EIPS/eip-7201), gas optimization)
- [x] https://github.com/sherlock-audit/2023-12-ubiquity-judging/issues/145 (don't allow admin to add 2 equal collateral addresses)
- [x] https://github.com/sherlock-audit/2023-12-ubiquity-judging/issues/156 (`transferFrom(receiver)` in deprecated contract, we can't leave it this way even if the contract is not used)
- [x] ~~https://github.com/sherlock-audit/2023-12-ubiquity-judging/issues/160~~ (pass `msg.value` in diamond's `delegatecall`, update: [invalid](https://github.com/ubiquity/ubiquity-dollar/issues/874#issuecomment-1976534572))
- [x] https://github.com/sherlock-audit/2023-12-ubiquity-judging/issues/183 (unauthorized fallback call with `msg.data.length < 4 bytes`)
- [x] https://github.com/sherlock-audit/2023-12-ubiquity-judging/issues/207 (Dollars can be minted for 0 collateral for low decimal collaterals)
- [x] https://github.com/sherlock-audit/2023-12-ubiquity-judging/issues/230 (wrong number of blocks in a week) . 

P.S. The list may be updated

**Comment by 0x4007** [comment]
Just to clarify @gitcoindev @molecula451 because of:

> P.S. The list may be updated

I think it makes sense to: 
1. Reopen those issues on the Sherlock repository [^1^]
2. Open pull requests to `@ubiquity/ubiquity-dollar` and write something like `Resolves https://github.com/sherlock-audit/2023-12-ubiquity-judging/issues/21` in the pull request body [^2^]

This is to keep things in sync. After our adjustments are completed, we can mirror the issues back to the `@ubiquity/ubiquity-dollar` repository as a backup for auditing purposes (in case Sherlock decides to delete their repository.)

You guys should delete the mirrored issues on this repository now. 

[^1^]: It is not clear to me why Sherlock closes them as complete. I suppose we technically can leave them closed as complete and still associate pull requests to them if it is a problem to reopen them. 
[^2^]: This automatically associates the issue with the pull request, which is useful for auditing in the future.

**Comment by molecula451** [comment]
Yeah, i think it makes sense, all the mirroed issues were taken down, point to PR to resolve to the Resolves `https://github.com/sherlock-audit/2023-12-ubiquity-judging/issues/X` number issue

**Comment by rndquu** [comment]
> Reopen those issues on the Sherlock repository

I don't think we should reopen them since those closed issues are considered invalid/low priority in terms of sherlock rules so the medium/high issues are only opened.

**Comment by gitcoindev** [comment]
> > Reopen those issues on the Sherlock repository
> 
> I don't think we should reopen them since those closed issues are considered invalid/low priority in terms of sherlock rules so the medium/high issues are only opened.

Cross-referencing them is a good practice. I am also not sure if Sherlock will keep this available forever, so we can mirror the issues back as @pavlovcik suggested, and skip reopening.

**Comment by molecula451** [comment]
By the sherklock repo it looks like they "archive" the whole judging repo, so i think we're fine with either way, mirroring now or mirroring later

**Comment by molecula451** [comment]
Recapping this one this issue posted here were closed specifically by the lead judge, i reopened one (to recheck) and he gave a reason to re-closed

**Comment by gitcoindev** [comment]
I am going to look into those issues and try to gradually fix them one by one starting tomorrow onward.

**Comment by 0x4007** [comment]
I should be able to enable payouts directly in their repository once I make time to figure out the permit wallet situation.

**Comment by rndquu** [comment]
> Update - this issue was marked invalid by Sherlock team

If some issue is marked as invalid by the Sherlock team it doesn't mean that we shouldn't fix it. Sherlock has pretty strict rules so only medium and high severity issues are considered valid hence the current "Audit: fix low severity issues" task was created specifically for low severity issues.

**Comment by gitcoindev** [comment]
> > Update - this issue was marked invalid by Sherlock team
> 
> If some issue is marked as invalid by the Sherlock team it doesn't mean that we shouldn't fix it. Sherlock has pretty strict rules so only medium and high severity issues are considered valid hence the current "Audit: fix low severity issues" task was created specifically for low severity issues.

All right, thank you for clarifying this, I update the description.

**Comment by molecula451** [comment]
rndqnuu the diamond it's not subceptible to reentraacy, i've seen others implementation live and they are working very well so https://github.com/sherlock-audit/2023-12-ubiquity-judging/issues/119 not need to be overlook

**Comment by rndquu** [comment]
> rndqnuu the diamond it's not subceptible to reentraacy, i've seen others implementation live and they are working very well so [sherlock-audit/2023-12-ubiquity-judging#119](https://github.com/sherlock-audit/2023-12-ubiquity-judging/issues/119) not need to be overlook

I don't think so, diamond does susceptible to reentrancy. Could you share some articles where it is stated that diamond is "reentrancy free"?

**Comment by molecula451** [comment]
> I don't think so, diamond does susceptible to reentrancy. Could you share some articles where it is stated that diamond is "reentrancy free"?

in the fallback function where this watson pointed that it's prone to reentrant, doesn't look like, basically he's poiting that we lack the nonReetrant here on the fallback

https://etherscan.io/address/0x32400084c286cf3e17e7b677ea9583e60a000324#code

for instance there is this diamond with a couple$ without this modifier, looks highly debuggged, you'd jack that pot if you reentrant the fallback there

and to me this submission was from an automated tool without manually check after so it looks as false positive

no modifier on the fallback deployed on chain either: https://github.com/aavegotchi/aavegotchi-contracts/blob/7db9b732466f9b6e9b22d669f313f495750935b1/contracts/Aavegotchi/ForgeDiamond/ForgeDiamond.sol#L30

**Comment by rndquu** [comment]
> > I don't think so, diamond does susceptible to reentrancy. Could you share some articles where it is stated that diamond is "reentrancy free"?
> 
> in the fallback function where this watson pointed that it's prone to reentrant, doesn't look like, basically he's poiting that we lack the nonReetrant here on the fallback
> 
> https://etherscan.io/address/0x32400084c286cf3e17e7b677ea9583e60a000324#code
> 
> for instance there is this diamond with a couple$ without this modifier, looks highly debuggged, you'd jack that pot if you reentrant the fallback there
> 
> and to me this submission was from an automated tool without manually check after so it looks as false positive
> 
> no modifier on the fallback deployed on chain either: https://github.com/aavegotchi/aavegotchi-contracts/blob/7db9b732466f9b6e9b22d669f313f495750935b1/contracts/Aavegotchi/ForgeDiamond/ForgeDiamond.sol#L30

As a part of https://github.com/sherlock-audit/2023-12-ubiquity-judging/issues/119 we don't need to add the `nonReentrant` modifier to the diamond's fallback but rather check all facets for this missing modifier ([here](https://github.com/ubiquity/ubiquity-dollar/blob/363cf41691e579e3a5acde19fb53d4e0aa7d0c18/packages/contracts/src/dollar/facets/UbiquityPoolFacet.sol#L77), [here](https://github.com/ubiquity/ubiquity-dollar/blob/363cf41691e579e3a5acde19fb53d4e0aa7d0c18/packages/contracts/src/dollar/facets/UbiquityPoolFacet.sol#L93), etc...)

**Comment by rndquu** [comment]
@gitcoindev Why did you mark https://github.com/sherlock-audit/2023-12-ubiquity-judging/issues/71 as invalid? Don't we need the `whenNotPaused()` modifier [here](https://github.com/ubiquity/ubiquity-dollar/blob/9f882429a844ca14118079c255368446bbafa8de/packages/contracts/src/dollar/facets/UbiquityPoolFacet.sol#L82), [here](https://github.com/ubiquity/ubiquity-dollar/blob/9f882429a844ca14118079c255368446bbafa8de/packages/contracts/src/dollar/facets/UbiquityPoolFacet.sol#L97) or [here](https://github.com/ubiquity/ubiquity-dollar/blob/9f882429a844ca14118079c255368446bbafa8de/packages/contracts/src/dollar/facets/UbiquityPoolFacet.sol#L109)?

**Comment by gitcoindev** [comment]
> @gitcoindev Why did you mark [sherlock-audit/2023-12-ubiquity-judging#71](https://github.com/sherlock-audit/2023-12-ubiquity-judging/issues/71) as invalid? Don't we need the `whenNotPaused()` modifier [here](https://github.com/ubiquity/ubiquity-dollar/blob/9f882429a844ca14118079c255368446bbafa8de/packages/contracts/src/dollar/facets/UbiquityPoolFacet.sol#L82), [here](https://github.com/ubiquity/ubiquity-dollar/blob/9f882429a844ca14118079c255368446bbafa8de/packages/contracts/src/dollar/facets/UbiquityPoolFacet.sol#L97) or [here](https://github.com/ubiquity/ubiquity-dollar/blob/9f882429a844ca14118079c255368446bbafa8de/packages/contracts/src/dollar/facets/UbiquityPoolFacet.sol#L109)?

Hi @rndquu ! I was guided by this comment https://github.com/sherlock-audit/2023-12-ubiquity-judging/issues/71#issuecomment-1900017138

In the library we have already `requires` to protect against mint / redeem, for the examples that you provided: 

https://github.com/ubiquity/ubiquity-dollar/blob/9f882429a844ca14118079c255368446bbafa8de/packages/contracts/src/dollar/libraries/LibUbiquityPool.sol#L356
https://github.com/ubiquity/ubiquity-dollar/blob/9f882429a844ca14118079c255368446bbafa8de/packages/contracts/src/dollar/libraries/LibUbiquityPool.sol#L428
https://github.com/ubiquity/ubiquity-dollar/blob/9f882429a844ca14118079c255368446bbafa8de/packages/contracts/src/dollar/libraries/LibUbiquityPool.sol#L499

My understanding was that this mechanism shall be used but theoretically, if you think it makes sense, we could add `whenNotPaused()` on top as well, please let me know, as adding the modifier is straightforward.

**Comment by molecula451** [comment]
yeah this would be code redundancy, let's re-check tests on this requires and if they're good then no need for `whenNotPaused()` modifier, avoid redundancy

**Comment by molecula451** [comment]
yeah this would be code redundancy, let's re-check tests on this requires and if they're good then no need for modifier, avoid redundancy

**Comment by rndquu** [comment]
> > @gitcoindev Why did you mark [sherlock-audit/2023-12-ubiquity-judging#71](https://github.com/sherlock-audit/2023-12-ubiquity-judging/issues/71) as invalid? Don't we need the `whenNotPaused()` modifier [here](https://github.com/ubiquity/ubiquity-dollar/blob/9f882429a844ca14118079c255368446bbafa8de/packages/contracts/src/dollar/facets/UbiquityPoolFacet.sol#L82), [here](https://github.com/ubiquity/ubiquity-dollar/blob/9f882429a844ca14118079c255368446bbafa8de/packages/contracts/src/dollar/facets/UbiquityPoolFacet.sol#L97) or [here](https://github.com/ubiquity/ubiquity-dollar/blob/9f882429a844ca14118079c255368446bbafa8de/packages/contracts/src/dollar/facets/UbiquityPoolFacet.sol#L109)?
> 
> Hi @rndquu ! I was guided by this comment [sherlock-audit/2023-12-ubiquity-judging#71 (comment)](https://github.com/sherlock-audit/2023-12-ubiquity-judging/issues/71#issuecomment-1900017138)
> 
> In the library we have already `requires` to protect against mint / redeem, for the examples that you provided:
> 
> https://github.com/ubiquity/ubiquity-dollar/blob/9f882429a844ca14118079c255368446bbafa8de/packages/contracts/src/dollar/libraries/LibUbiquityPool.sol#L356
> 
> 
> https://github.com/ubiquity/ubiquity-dollar/blob/9f882429a844ca14118079c255368446bbafa8de/packages/contracts/src/dollar/libraries/LibUbiquityPool.sol#L428
> 
> 
> https://github.com/ubiquity/ubiquity-dollar/blob/9f882429a844ca14118079c255368446bbafa8de/packages/contracts/src/dollar/libraries/LibUbiquityPool.sol#L499
> 
> My understanding was that this mechanism shall be used but theoretically, if you think it makes sense, we could add `whenNotPaused()` on top as well, please let me know, as adding the modifier is straightforward.

Yes, you're right, I've totally forgotten that https://github.com/ubiquity/ubiquity-dollar/blob/development/packages/contracts/src/dollar/libraries/LibUbiquityPool.sol has its own pause mechanic. It's ok then to mark https://github.com/sherlock-audit/2023-12-ubiquity-judging/issues/71 as invalid.

**Comment by rndquu** [comment]
Marking https://github.com/sherlock-audit/2023-12-ubiquity-judging/issues/160 as invalid because:
1. Yul's `delegatecall()` doesn't have `msg.value` in params (check the [docs](https://docs.soliditylang.org/en/latest/yul.html) and related SO question [here](https://ethereum.stackexchange.com/questions/102605/why-cant-you-specify-the-message-value-when-using-delegatecall))
2. I've double checked our Diamond implementation, all payable methods are working fine (i.e. accept ETH if you send it)
